=== uo293820/MotoGP-Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es"
			elementFormDefault="qualified"
			targetNamespace="http://www.uniovi.es"
			xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="pais" />
				<xs:element ref="localidad" />
				<xs:element ref="longitudCircuito" />
				<xs:element ref="anchuraMedia" />
				<xs:element ref="carrera" />
				<xs:element ref="ubicacion" />
				<xs:element ref="referencias" />
				<xs:element ref="media" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="nombre" type="xs:string" />

	<xs:element name="pais" type="xs:string" />

	<xs:element name="localidad" type="xs:string" />

	<xs:element name="longitudCircuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidades" use="required" type="xs:string">
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="anchuraMedia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidades" use="required" type="xs:string">
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="carrera">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fecha" />
				<xs:element ref="horaEspaña" />
				<xs:element ref="vueltas" />
				<xs:element ref="patrocinador" />
				<xs:element ref="resultado" />
				<xs:element ref="clasificacionMundial" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="fecha" type="xs:date" />

	<xs:element name="horaEspaña" type="xs:time" />

	<xs:element name="vueltas">
		<xs:simpleType>
			<xs:restriction base="xs:positiveInteger">
				<xs:minInclusive value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="patrocinador" type="xs:string" />

	<xs:element name="resultado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="vencedor" />
				<xs:element ref="tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="vencedor" type="xs:string" />

	<xs:element name="tiempo" type="xs:duration" />

	<xs:element name="clasificacionMundial">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="posicion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="posicion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="piloto" />
			</xs:sequence>
			<xs:attribute name="numero" use="required" type="xs:positiveInteger">
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="piloto" type="xs:string" />
	
	<xs:element name="ubicacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="origen" />
				<xs:element ref="trazado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="origen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Tipo simple para poder aplicar restricciones al elemento "longitud" -->
	<xs:simpleType name="LongitudRestriccion">
  		<xs:restriction base="xs:decimal">
   			<xs:minInclusive value="-180"/>
    		<xs:maxInclusive value="180"/>
  		</xs:restriction>
	</xs:simpleType>

	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="LongitudRestriccion">
					<xs:attribute name="unidades"
									use="required"
									type="xs:string"
									fixed="grados">
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<!-- Tipo simple para poder aplicar restricciones al elemento "latitud" -->
	<xs:simpleType name="LatitududRestriccion">
  		<xs:restriction base="xs:decimal">
   			<xs:minInclusive value="-90"/>
    		<xs:maxInclusive value="90"/>
  		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="LatitududRestriccion">
					<xs:attribute name="unidades"
									use="required"
									type="xs:string"
									fixed="grados">
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<!-- Tipo simple para poder aplicar restricciones al elemento "altitud" -->
	<xs:simpleType name="AltitudRestriccion">
  		<xs:restriction base="xs:decimal">
   			<xs:minInclusive value="0"/>
  		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="AltitudRestriccion">
					<xs:attribute name="unidades"
									use="required"
									type="xs:string"
									fixed="metros sobre el nivel del mar">
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="trazado">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidades"
									use="required"
									type="xs:string"
									fixed="metros">
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="sector">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1"/>
				<xs:maxInclusive value="4"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="ref" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="ref" type="xs:anyURI" />
	
	<xs:element name="media">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fotos" />
				<xs:element ref="videos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="foto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:anyURI">
					<xs:attribute name="descripción" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="video">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:anyURI">
					<xs:attribute name="descripción" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== uo293820/MotoGP-Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>

<circuito xmlns="http://www.uniovi.es"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.uniovi.es circuito.xsd">

    <nombre>Sachsenring</nombre>
    <pais>Alemania</pais>
    <localidad>Hohenstein-Ernstthal</localidad>

    <longitudCircuito unidades="metros">3671</longitudCircuito>
    <anchuraMedia unidades="metros">12</anchuraMedia>

    <carrera>
        <fecha>2025-07-13</fecha>
        <horaEspaña>14:00:00</horaEspaña>
        <vueltas>30</vueltas>
        <patrocinador>Liqui Moly Grand Prix of Germany 2025</patrocinador>
        <resultado>
            <vencedor>Marc Márquez</vencedor>
            <tiempo>PT40M42.854S</tiempo>
        </resultado>
        <clasificacionMundial>
            <posicion numero="1">
                <piloto>Marc Márquez</piloto>
            </posicion>
            <posicion numero="2">
                <piloto>Álex Márquez</piloto>
            </posicion>
            <posicion numero="3">
                <piloto>Francesco Bagnaia</piloto>
            </posicion>
        </clasificacionMundial>
    </carrera>

    <ubicacion>

        <origen>
            <longitud unidades="grados">12.68807724922379</longitud>
            <latitud unidades="grados">50.79175728835934</latitud>
            <altitud unidades="metros sobre el nivel del mar">330.9438399535764</altitud>
        </origen>

        <trazado>
            <tramo>
                <distancia unidades="metros">85.91</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.68908061890597</longitud>
                    <latitud unidades="grados">50.79219826200591</latitud>
                    <altitud unidades="metros sobre el nivel del mar">332.3669225791181</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">84.72</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69007240802596</longitud>
                    <latitud unidades="grados">50.79263084800947</latitud>
                    <altitud unidades="metros sobre el nivel del mar">334.4603283370987</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">78.72</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.6910001975818</longitud>
                    <latitud unidades="grados">50.7930274212857</latitud>
                    <altitud unidades="metros sobre el nivel del mar">334.5345884006572</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">57.98</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69170307082403</longitud>
                    <latitud unidades="grados">50.79330017934584</latitud>
                    <altitud unidades="metros sobre el nivel del mar">335.4062007700873</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">22.25</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69201681957707</longitud>
                    <latitud unidades="grados">50.79332698962793</latitud>
                    <altitud unidades="metros sobre el nivel del mar">335.5130354896287</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">19.52</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69227305806282</longitud>
                    <latitud unidades="grados">50.79325955265985</latitud>
                    <altitud unidades="metros sobre el nivel del mar">334.8242575063368</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">18.07</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69244784199091</longitud>
                    <latitud unidades="grados">50.79314097118925</latitud>
                    <altitud unidades="metros sobre el nivel del mar">333.4660519861164</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">18.21</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69250143269344</longitud>
                    <latitud unidades="grados">50.79298113560176</latitud>
                    <altitud unidades="metros sobre el nivel del mar">332.1979264222489</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">19.04</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69242782530024</longitud>
                    <latitud unidades="grados">50.79281644265767</latitud>
                    <altitud unidades="metros sobre el nivel del mar">331.5182076152981</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">22.55</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69221304501131</longitud>
                    <latitud unidades="grados">50.79266609018845</latitud>
                    <altitud unidades="metros sobre el nivel del mar">330.5741036809558</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">20.77</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69202609504088</longitud>
                    <latitud unidades="grados">50.79252167323293</latitud>
                    <altitud unidades="metros sobre el nivel del mar">329.7032567707009</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">18.91</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69189574972202</longitud>
                    <latitud unidades="grados">50.79237302696035</latitud>
                    <altitud unidades="metros sobre el nivel del mar">329.0037242978417</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">20.50</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69180568089069</longitud>
                    <latitud unidades="grados">50.79219788168108</latitud>
                    <altitud unidades="metros sobre el nivel del mar">328.0336586837496</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">20.09</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69176362927152</longitud>
                    <latitud unidades="grados">50.79201927917431</latitud>
                    <altitud unidades="metros sobre el nivel del mar">327.2412011179225</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">21.78</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69179018834349</longitud>
                    <latitud unidades="grados">50.79182428476399</latitud>
                    <altitud unidades="metros sobre el nivel del mar">326.4938636099811</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">21.40</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69187102511386</longitud>
                    <latitud unidades="grados">50.79163893799345</latitud>
                    <altitud unidades="metros sobre el nivel del mar">325.5823091947344</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">25.90</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69209235126161</longitud>
                    <latitud unidades="grados">50.79145316944232</latitud>
                    <altitud unidades="metros sobre el nivel del mar">324.0798677167049</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">26.52</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69241377347812</longitud>
                    <latitud unidades="grados">50.79132957881314</latitud>
                    <altitud unidades="metros sobre el nivel del mar">322.0645358294859</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">20.64</distancia>
                <coordenadas>
                    <longitud unidades="grados">12.69269283456777</longitud>
                    <latitud unidades="grados">50.79127391638879</latitud>
                    <altitud unidades="metros sobre el nivel del mar">320.3103133508519</altitud>
                </coordenadas>
                <sector>1</sector>
